### ISSUE TITLE
Introducing the confectory-datamapper-lite module

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#12]
### Proposed solution

Introducing a new module `confectory-datamapper-lite` (the name may still be updated) for mapping JSON sources and converting Properties and XML into JSON.

<table>
<tr>
<th>Module</th>
<th>Provider(s)</th>
<th>Properties</th>
<th>XML</th>
<th>JSON</th>
<th>YAML</th>
<tr>
<td>confectory-datamapper-lite*</td>
<td>JSON-Java + JayWay JSONPath</td>
<td>YES</td>
<td>YES</td>
<td>YES</td>
<td>--</td>
</tr>
</table>

##### Sample file (agents.json)

````json
{
  "enabled": true,
  "agents": [
    {
      "class": "Agent1",
      "interval": "*/2 * * * *"
    },
    {
      "class": "Agent2",
      "interval": "10s"
    }
  ]
}

````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JSONObject>builder()
                                .source(new ClasspathFileSource<>("agents.json"))
                                .mapper(new JSONObjectMapper())
                                .build();

config.getBean(); // returns a JSONObject
config.getBooleanProperty("$.enabled");        // JSONPath -- to be implemented in a dedicated issue
config.getStringProperty("$.agents[0].class"); // JSONPath -- to be implemented in a dedicated issue
````

**NOTE:** JSONPath support will be introduced in a dedicated issue

### Task list

The following requirements shall be addressed in this issue:

- [x] Create a new module project `confectory-datamapper-lite` (dependent on `confectory-core`)
- [x] New concrete `Mapper` implementation (suggested name: `JSONObjectMapper`) for loading JSON sources (as `JSONObjects`)
- [x] New concrete `Mapper` implementation (suggested name: `XMLtoJSONObjectMapper`) for loading XML sources as `JSONObjects`
- [x] New concrete `Mapper` implementation (suggested name: `PropertiesToJSONObjectMapper`) for loading .properties sources as `JSONObjects`
- [x] New `Reader` interface, with a concrete `JSONObjectReader` implementation (with the `getBean()` method implemented but the other methods should throw an `UnsupportedOperationException` for now)

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0012`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
