### ISSUE TITLE
Retrieving JSON configuration data with JSONPath

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#13]
### Proposed solution

This issue is dedicated to adding JSONPath support to `confectory-datamapper-core` so that configuration data from JSON objects (as well as converted XML and Properties sources) can be retrieved using JSON Path.

##### Sample file (agents.json)

````json
{
  "enabled": true,
  "agents": [
    {
      "class": "Agent1",
      "interval": "*/2 * * * *"
    },
    {
      "class": "Agent2",
      "interval": "10s"
    }
  ]
}

````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JSONObject>builder()
                                .source(new ClasspathFileSource<>("agents.json"))
                                .mapper(new JSONObjectMapper())
                                .build();

config.getBean(); // returns a JSONObject
config.getBooleanProperty("$.enabled");        // true
config.getStringProperty("$.agents[0].class"); // "Agent1"
````

**NOTE:** This issue depends on #12.

### Task list

The following requirements shall be addressed in this issue:

- [ ] Add JayWay JSONPath dependency inside `confectory-core` POM file.
- [ ] Add new methods in the `ConfigurationHelper` interface for retrieving objects from a key/path
  - [ ] `T getObject(String)` which reads a JSONPath and returns a generic object (e.g.: `JSONObject` for `ConfigurationHelper<JSONObject>`) from the JSON
  - [ ] `List<T> getList(String)` which reads a JSONPath and returns an ArrayList of generic objects (e.g.: `ArrayList<JSONObject>` for `ConfigurationHelper<JSONObject>`) from the JSON
  - [ ] Add default (no-op) implementations for existing ConfigurationHelpers introduced in 0.1.0
  - [ ] Add a new concrete `JSONObjectConfigurationHelper` implementation which evaluates JSON paths and retrieve data
- [ ] Add new JUnits
- [ ] Update JUnits (modified helpers)

**IMPORTANT**: Avoid using static JSONPath configuration to allow multiple JSON providers planned on future releases

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0013`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
