### ISSUE TITLE
Introducing the confectory-datamapper-jackson2 module

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#14]
### Proposed solution

Introducing a new module `confectory-datamapper-jackson2` (the name may still be updated) for mapping JSON sources using Jackson 2 either as Jackson's JSON object implementation or as a user-defined bean.

<table>
<tr>
<th>Module</th>
<th>Provider(s)</th>
<th>Properties</th>
<th>XML</th>
<th>JSON</th>
<th>YAML</th>
<tr>
<td>confectory-datamapper-jackson2*</td>
<td>Jackson 2</td>
<td>--</td>
<td>--</td>
<td>YES</td>
<td>--</td>
</tr>
</table>

##### Sample file (agents.json)

````json
{
  "enabled": true,
  "agents": [
    {
      "class": "Agent1",
      "interval": "*/2 * * * *"
    },
    {
      "class": "Agent2",
      "interval": "10s"
    }
  ]
}

````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JsonObject>builder()
                                .source(new ClasspathFileSource<>("agents.json"))
                                .mapper(new JacksonJsonObjectMapper())
                                .build();

config.getBean(); // returns a Jackson's JsonObject
config.getBooleanProperty("$.enabled");        // true
config.getStringProperty("$.agents[0].class"); // "Agent1"
````

### Task list

The following requirements shall be addressed in this issue:

- [ ] Create a new module project `confectory-datamapper-jackson2` (dependent on `confectory-core`)
- [ ] New concrete `Mapper` implementation (suggested name: `JacksonJsonObjectMapper`) for loading JSON sources (as Jackson's `JsonObjects`)
- [ ] New `Reader` interface, with a concrete `JacksonJsonObjectReader` implementation (all methods implemented)
- [ ] Do the applicable refactorings to avoid duplicated coding 
- [ ] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0013`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
