### ISSUE TITLE
Introducing the confectory-datamapper-gson2 module

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#17]
### Proposed solution

Introducing a new module `confectory-datamapper-gson2` (the name may still be updated) for mapping JSON sources either as GSON's default JSON object implementation or as a user-defined bean.

The new module shall be dependent on `confectory-datamapper-core` (this condition may be updated in the future).

<table>
<tr>
<th>Module</th>
<th>Provider(s)</th>
<th>Properties</th>
<th>XML</th>
<th>JSON</th>
<th>YAML</th>
<tr>
<td>confectory-datamapper-gson*</td>
<td>GSON</td>
<td>--</td>
<td>--</td>
<td>YES</td>
<td>--</td>
</tr>
</table>

##### Sample file (agents.json)

````json
{
  "enabled": true,
  "agents": [
    {
      "class": "Agent1",
      "interval": "*/2 * * * *"
    },
    {
      "class": "Agent2",
      "interval": "10s"
    }
  ]
}
````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JSONObject>builder() // ???
                                .source(new ClasspathFileSource<>("agents.json"))
                                .mapper(new GsonMapper())
                                .build();

config.getBean(); // returns a GSON's JSON object
config.getBooleanProperty("$.enabled");        // true
config.getStringProperty("$.agents[0].class"); // "Agent1"
````

### Task list

The following requirements shall be addressed in this issue:

- [x] Create a new module project `confectory-datamapper-gson2`
- [x] New concrete `Mapper` implementation (suggested name: `GsonMapper`) for loading JSON sources as GSON's JSON Object
- [x] New concrete `Mapper` implementation (suggested name: `GsonToObjectMapper`) for loading JSON sources as POJO
- [x] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0017`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
