### ISSUE TITLE
[confectory-core] New JSONObjectConfigurationMerger

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#20]
### Proposed solution

Enhancing the `confectory-core` with a new specialized `ConfigurationMerger` for JSON Objects (using json-smart provider).

##### File 1 (file1.json)

````json
{
  "agents": [
    {
      "class": "Agent1",
      "interval": "*/2 * * * *"
    },
    {
      "class": "Agent2",
      "interval": "90s"
    }
  ]
}
````

##### File 2 (file2.json)

````json
{
  "enabled": true,
  "agents": [
    {
      "class": "Agent2",
      "interval": "10s"
    }
  ]
}
````

##### Code sample (desired):

```` java
Configuration<JSONObject> config1 = Configuration.<JSONObject>builder()
                                .source(new ClasspathFileSource<>("file1.json"))
                                .mapper(new JSONObjectMapper())
                                .precedence(9) // higher precedence
                                .build();

Configuration<JSONObject> config2 = Configuration.<JSONObject>builder()
                                .source(new ClasspathFileSource<>("file2.json"))
                                .mapper(new JSONObjectMapper())
                                .precedence(1) // lower precedence
                                .build();

Configuration<JSONObject> merged = new JSONObjectConfigurationMerger()
                                .withMergeOptions( // accept varargs
                                     MergeOption.distinctObjectsIdentifiedByAttribute("class")
                                         .insideArray("$['agents']") // jsonpath
                                .merge(config1, config2);

merged.getBean(); // returns a JSONObject
merged.getBooleanProperty("$.enabled"); // true (from config2)
merged.getStringProperty("$.*[?(@.class=='Agent1')].interval"); // "*/2 * * * *", as from config1
merged.getStringProperty("$.*[?(@.class=='Agent2')].interval"); // "90s", as config1 has higher precedence
````

Some comments on the `withDistinctSet()` method:
- By default, all root elements on the JSON object could be considered distinct/unique, but objects in any other level in the JSON tree (e.g. inside an array or other objects) which should be considered distinct/unique (such as the agent class attribute, in the example above) should be informed to the merger.
- The merger shall **NOT** rely on the position of elements inside an array to do the merge

### Task list

The following requirements shall be addressed in this issue:

- [x] Create a new concrete `JSONObjectConfigurationMerger`, which performs merging of two `Configuration<JSONObject>` objects.
- [x] Implement custom merging of JSONObjects inside JSONArray, based on distinct object keys for conflict handling
- [ ] Implement the `MergeOption` class, with fluent API for declaring distinct object keys inside an array
- [ ] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0020`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable

**Comment by oswaldobapvicjr** [comment]
The fluent API `MergeOptions` suggestion was postponed and will be handled in a future issue. For now, the hash map of distinct keys by array path can be used for the same purpose with no problems.
