### ISSUE TITLE
New ConfigurationContainer data fetch strategies

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#24]
### Background

With the introduction of enhancement #6, it's now possible to retrieve data from multiple Configuration objects seamlessly passing a namespace and key.

However, the namespace is optional. So, in a ConfigurationContainer, the user shall retrieve data from Configuration objects without a namespace by using the single-argument getter methods.

Examples:
````java
container.getStringProperty("key1"); // retrieves data from configurations without namespace
container.getStringProperty("namespace1", "key1"); // retrieves data from configurations of namespace "namespace1"
````

### Proposed solution

Introducing two different data fetch strategies inside a ConfigurationContainer to be applied when the single-argument getter methods are called (i.e., without a specific namespace):

- **STRICT**: Retrieves data from Configuration objects without namespace only (current behavior; default)
- **LENIENT**: Retrieves data from all Configuration objects, i.e., disregard the namespaces (alternative strategy)

**NOTES:**

- **1**: This setting is totally optional and basic usability shall not be affected by this enhancement.
- **2**: The default data fetch strategy shall be configurable inside the global `ConfectoryConfiguration` object.

##### Code sample (desired):

```` java
ConfigurationContainer container1 = new ConfigurationContainer(DataFetchStrategy.STRICT, <configs...>);
ConfigurationContainer container2 = new ConfigurationContainer(DataFetchStrategy.LENIENT, <configs...>);
ConfigurationContainer container3 = new ConfigurationContainer(<configs...>); // uses default configured data fetch strategy

container1.getStringProperty("key1"); // queries configuration without namespace only
container2.getStringProperty("key1"); // queries all configuration objects regardless of namespace
````

### Task list

The following requirements shall be addressed in this issue:

- [x] Create the `DataFetchStrategy` enum with the Strict behavior
- [x] Create the `DataFetchStrategy` enum with the Lenient behavior
- [x] Setup the default data fetch strategy configuration at `ConfectoryConfiguration`
- [x] Integrate the `DataFetchStrategy` with the `ConfigurationFactory` class
- [x] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0024`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
