### ISSUE TITLE
Preparing for release 0.1.0

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#29]
### Proposed solution

This issue is intended to address minor improvements before the release of Confectory 0.1.0.

### Task list

The following requirements shall be addressed in this issue:

- [x] Add Javadoc overview page
- [x] Add package-level Javadocs
- [x] Review class Javadocs (fix typos/add relevant examples)
- [x] Setup custom CSS for gerenated Javadoc pages
- [x] Fix typos in POM.xml file/review POM structure

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0029`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
