### ISSUE TITLE
New module confectory-datamapper-snakeyaml

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#61]
### Proposed solution

Introducing a new module `confectory-datamapper-snakeyaml` (the name may still be updated) for mapping YAML sources either as JSONObject (minidev's smart-json, which is a hashmap and allows for JSONPath) or as a user-defined bean.

The new module shall be dependent on `confectory-datamapper-core`.

<table>
<tr>
<th>Module</th>
<th>Provider(s)</th>
<th>Properties</th>
<th>XML</th>
<th>JSON</th>
<th>YAML</th>
<tr>
<td>confectory-datamapper-snakeyaml</td>
<td>SnakeYAML</td>
<td>--</td>
<td>--</td>
<td>?</td>
<td>YES</td>
</tr>
</table>

##### Sample file (customer.yaml)

````yaml
firstName: John
lastName: Doe
age: 31
height: 1.75
contactDetails:
   - type: mobile
     number: 123456789
   - type: landline
     number: 456786868
homeAddress:
   line: 123, ABC Street
   city: City Y
   state: State Y
   zip: 345657
````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JSONObject>builder() // minidev's smart-json
                                .source(new ClasspathFileSource<>("customer.yaml"))
                                .mapper(new YAMLToJSONObjectMapper())
                                .build();

config.getBean(); // returns a smart JSON object (assignable from HashMap)
config.getString("$.contactDetails[?(@.type=='landline')].number"); // 456787878
````

### Task list

The following requirements shall be addressed in this issue:

- [x] Create a new module project `confectory-datamapper-snakeyaml`
- [x] New concrete `Mapper` implementation (suggested name: `YAMLToJSONObjectMapper`) for loading JSON sources as JSON Object
- [x] New concrete `Mapper` implementation (suggested name: `YAMLToObjectMapper`) for loading JSON sources as POJO
- [x] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0017`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
