### ISSUE TITLE
New module confectory-datamapper-jackson2-toml

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/confectory#63]
### Proposed solution

Introducing a new module `confectory-datamapper-jackson2-toml` for mapping TOML sources using Jackson 2 either as Jackson's JsonNode implementation or as a user-defined bean.

The new module shall be dependent on `confectory-datamapper-jackson2`.

<table>
<tr>
<th>Module</th>
<th>Provider(s)</th>
<th>Properties</th>
<th>XML</th>
<th>JSON</th>
<th>YAML</th>
<th>TOML</th>
<tr>
<td>confectory-datamapper-jackson2-toml*</td>
<td>Jackson 2 + TOML dataformat</td>
<td>--</td>
<td>--</td>
<td>YES</td>
<td>--</td>
<td>YES</td>
</tr>
</table>

##### Sample file (university.toml)

````toml
[university]
  name = "University of London"
  country = "United Kingdom"
  [university.department]
    name = "Electrical Engineering"
    students = 2750
    subjects = ["Mathematics","Control Systems","Power Systems"]
````

##### Code sample (desired):

```` java
Configuration config = Configuration.<JsonNode>builder()
                                .source(new ClasspathFileSource<>("university.toml"))
                                .mapper(new JacksonTOMLToJsonNodeMapper())
                                .build();

config.getBean(); // returns a Jackson's JsonNode
config.getString("$.university.country"); // United Kingdom
config.getString("$.university.department.students"); // 2750 
````

### Task list

The following requirements shall be addressed in this issue:

- [x] Create a new module project `confectory-datamapper-jackson2-toml` (dependent on `confectory-datamapper-jackson2`)
- [x] New concrete `Mapper` implementation to load TOML sources as Jackson's `JsonObjects`
- [x] New concrete `Mapper` implementation to load TOML sources and user-defined beans)
- [x] JUnits

## Additional details
- The code shall be developed in a dedicated branch, with the prefix `issue/` followed by the issue number (e.g.: `issue/0016`)

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable
